#!/bin/bash
# Pi-Commander Configuration Wizard
# Simplifies initial setup with interactive prompts

set -e

BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}🚀 Pi-Commander Configuration Wizard${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "${YELLOW}This wizard will help you configure your core infrastructure${NC}"
echo ""

# Detect server IP
SERVER_IP=$(hostname -I | awk '{print $1}')
echo -e "${GREEN}✓ Detected server IP: ${SERVER_IP}${NC}"
echo ""

# ====================
# DNS Provider Choice
# ====================
echo -e "${BLUE}[1/5] DNS Configuration${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Choose your DNS provider:"
echo "  1) Cloudflare (recommended if you have a domain)"
echo "  2) DuckDNS (free *.duckdns.org subdomain)"
echo ""
read -p "Enter choice [1-2]: " dns_choice

case $dns_choice in
  1)
    echo ""
    echo -e "${GREEN}Using Cloudflare${NC}"
    read -p "Enter your domain (e.g., example.com): " DOMAIN
    read -p "Enter Cloudflare API Token: " CF_API_TOKEN
    read -p "Enter Cloudflare Zone ID: " CF_ZONE_ID
    
    USE_CLOUDFLARE=true
    USE_DUCKDNS=false
    ;;
  2)
    echo ""
    echo -e "${GREEN}Using DuckDNS${NC}"
    read -p "Enter desired subdomain (e.g., myhomelab): " DUCKDNS_SUBDOMAIN
    read -p "Enter DuckDNS token: " DUCKDNS_TOKEN
    
    DOMAIN="${DUCKDNS_SUBDOMAIN}.duckdns.org"
    USE_CLOUDFLARE=false
    USE_DUCKDNS=true
    ;;
  *)
    echo -e "${RED}Invalid choice${NC}"
    exit 1
    ;;
esac

echo ""
echo -e "${GREEN}✓ Domain: ${DOMAIN}${NC}"
echo ""

# ====================
# VPN Configuration
# ====================
echo -e "${BLUE}[2/5] VPN Configuration${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Do you want to set up Twingate VPN for remote access?"
echo "  y) Yes (requires Twingate account)"
echo "  n) No (skip VPN setup)"
echo ""
read -p "Enable VPN [y/N]: " vpn_choice

if [[ "$vpn_choice" =~ ^[Yy]$ ]]; then
  echo ""
  read -p "Twingate Network Name: " TWINGATE_NETWORK
  read -p "Access Token: " TWINGATE_ACCESS_TOKEN
  read -p "Refresh Token: " TWINGATE_REFRESH_TOKEN
  ENABLE_VPN=true
else
  ENABLE_VPN=false
  echo -e "${YELLOW}Skipping VPN setup${NC}"
fi

echo ""

# ====================
# Email Notifications
# ====================
echo -e "${BLUE}[3/5] Email Notifications (Optional)${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
read -p "Enter your email for notifications (or press Enter to skip): " ADMIN_EMAIL

if [ -z "$ADMIN_EMAIL" ]; then
  ADMIN_EMAIL="admin@example.com"
  echo -e "${YELLOW}Using default: ${ADMIN_EMAIL}${NC}"
fi

echo ""

# ====================
# Timezone
# ====================
echo -e "${BLUE}[4/5] Timezone${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Current timezone: $(timedatectl show --property=Timezone --value)"
read -p "Enter timezone (or press Enter to keep current): " TZ_INPUT

if [ -z "$TZ_INPUT" ]; then
  TIMEZONE=$(timedatectl show --property=Timezone --value)
else
  TIMEZONE="$TZ_INPUT"
fi

echo -e "${GREEN}✓ Using timezone: ${TIMEZONE}${NC}"
echo ""

# ====================
# Confirmation
# ====================
echo -e "${BLUE}[5/5] Review Configuration${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Please review your configuration:"
echo ""
echo "  Domain:         ${DOMAIN}"
echo "  DNS Provider:   $([ "$USE_CLOUDFLARE" = true ] && echo "Cloudflare" || echo "DuckDNS")"
echo "  VPN Enabled:    $([ "$ENABLE_VPN" = true ] && echo "Yes" || echo "No")"
echo "  Admin Email:    ${ADMIN_EMAIL}"
echo "  Timezone:       ${TIMEZONE}"
echo "  Server IP:      ${SERVER_IP}"
echo ""
read -p "Proceed with this configuration? [Y/n]: " confirm

if [[ "$confirm" =~ ^[Nn]$ ]]; then
  echo -e "${RED}Configuration cancelled${NC}"
  exit 1
fi

# ====================
# Generate Config Files
# ====================
echo ""
echo -e "${BLUE}Generating configuration files...${NC}"

# NPM Config
mkdir -p docker/nginx-proxy-manager
cat > docker/nginx-proxy-manager/.env << EOF
# Generated by config-wizard.sh
TZ=${TIMEZONE}
NGINX_PROXY_HTTP=80
NGINX_PROXY_ADMIN=81
NGINX_PROXY_HTTPS=443
INITIAL_ADMIN_EMAIL=${ADMIN_EMAIL}
INITIAL_ADMIN_PASSWORD=changeme
EOF

# AdGuard Config
mkdir -p docker/adguard
cat > docker/adguard/.env << EOF
# Generated by config-wizard.sh
TZ=${TIMEZONE}
ADGUARD_DNS_TCP=53
ADGUARD_DNS_UDP=53
ADGUARD_SETUP_PORT=3001
ADGUARD_WEB_PORT=3000
ADGUARD_HTTPS_PORT=8443
ADGUARD_DOT_PORT=853
EOF

# Cloudflare DDNS Config
if [ "$USE_CLOUDFLARE" = true ]; then
  mkdir -p docker/cloudflare-ddns
  cat > docker/cloudflare-ddns/.env << EOF
# Generated by config-wizard.sh
CF_API_TOKEN=${CF_API_TOKEN}
CF_ZONE_ID=${CF_ZONE_ID}
CF_DOMAIN=${DOMAIN}
CF_SUBDOMAIN=@
CF_PROXIED=true
EOF
fi

# DuckDNS Config
if [ "$USE_DUCKDNS" = true ]; then
  mkdir -p docker/duckdns
  cat > docker/duckdns/.env << EOF
# Generated by config-wizard.sh
DUCKDNS_SUBDOMAIN=${DUCKDNS_SUBDOMAIN}
DUCKDNS_TOKEN=${DUCKDNS_TOKEN}
TZ=${TIMEZONE}
EOF
fi

# Twingate Config
if [ "$ENABLE_VPN" = true ]; then
  mkdir -p docker/twingate
  cat > docker/twingate/.env << EOF
# Generated by config-wizard.sh
TWINGATE_NETWORK=${TWINGATE_NETWORK}
TWINGATE_ACCESS_TOKEN=${TWINGATE_ACCESS_TOKEN}
TWINGATE_REFRESH_TOKEN=${TWINGATE_REFRESH_TOKEN}
EOF
fi

echo ""
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${GREEN}✓ Configuration complete!${NC}"
echo -e "${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo "Next steps:"
echo "  1. Run: make deploy-all"
echo "  2. Access NPM: http://${SERVER_IP}:81"
echo "  3. Configure your first site in NPM"
echo "  4. Add SSL certificate in NPM"
echo ""
echo -e "${YELLOW}Important: Change the default NPM password after first login!${NC}"
echo ""
